name: ontrail-dl
dependencies:
- python=3.5.2
- openblas=0.2.14
- pandas=0.18.1
- scipy=0.17.0
- notebook=4.2.1
- ipython-notebook=4.0.4
- pymongo=3.0.3
- pytest
- ipython=4.2.0
- matplotlib=1.5.1
- blosc=1.2.3
- pillow=3.2.0
- scikit-learn=0.17.1
- pip
- pip:
  - https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py3-none-any.whl
  - configargparse==0.10.0
  - urllib3==1.14
  - neobunch==2.0.2
